# Choose Your Own Adventure
# Elyne Chao
# 24 September

# Choose your own adventure story focusing
# on using variables and branching/conditionals

# Obtain players username and store it
import time

user_name = input("Please enter your username.")
print(f"Nice to meet you {user_name}!")
print("Alright, let's begin.")
time.sleep(1)

# # Inroduction
print(f"{user_name}, you are an adventurer known for your bravery.")
time.sleep(2)
print("One day, you find a journal from an another adventurer who went missing a couple of years ago.")
time.sleep(2)
print("In the journal are clues to an ancient relic that is said to grant immense knowledge and power.")
time.sleep(2)
print("You pack your gear and begin to head for the jungle.")
time.sleep(4)

print("As you enter the jungle, two paths lie before you. You must pick which path to take.")
time.sleep(2)
print("Path A: A winding trail beside a river, it is calm and shaded, but slow.")
time.sleep(1)
print("Path B: A direct route through the dense jungle undergrowth, faster, but uncharted.")
time.sleep(2)
choice = input("Which path would you like to take?")
if choice == "A":
    print("As you walk into Path A, you refill your water and rest often. Then, you find a broken compass and a torn piece of a map stuck to a tree with a knife.")
    time.sleep(2)
    print("Just ahead. the river splits into two.")
    time.sleep(1)
    print("Path A1: Follow the left fork, which descends into a misty gorge.")
    time.sleep(1)
    print("Path A2: Follow the right fork, heading into higher ground.")
    choice_2 = input("Which path would you like to take?")
    if choice_2 == "A1":
        print("The gorge is cool and eerie. You pot ancient ruins half-buried in the mist.")
        time.sleep(2)
        print("There's a stone door carved into the side of a clif, marked with handprints and glyphs.")
        time.sleep(2)
        print("You place your hand on the stone. The door slides open...")
        time.sleep(2)
        print("Inside is a puzzle room, where you must align three spinning rings to match a symbol from the journal.")
        time.sleep(2)
        print("You succeed.")
        time.sleep(2)
        print("A hidden chamber opens, revealing a silver artifact.")
        time.sleep(2)
        print("The Relic you have been searching for.")
        time.sleep(2)
        print("The moment you touch it, knowledge floods your mind: languages, maps, visions of other forgotten relics.")
        time.sleep(2)
        print("You've found it.")
        time.sleep(2)
        print("You return to the world forever changed.")
        time.sleep(2)
        print("ENDING: THE SEEKER'S REWARD (GOOD ENDING)")
    elif choice_2 == "A2":
        print("You follow the path upward, eventually finding a campsite.")
        time.sleep(2)
        print("It’s abandoned, but there’s a journal left behind")
        time.sleep(2)
        print("The last entry reads:")
        time.sleep(2)
        print("The relic corrupts. Don’t touch it. Bury it. Forget it.")
        time.sleep(2)
        print("You push forward, eventually reaching the shrine. The relic glows on a pedestal. You hesitate.")
        time.sleep(2)
        print("A2a: Take it anyway.")
        time.sleep(2)
        print("A2b: Leave it untouched.")
        choice_3 = input("What would you like to do?")
        if choice_3 == "A2a":
            print("Your dreams become haunted.")
            time.sleep(2)
            print("You see visions of the jungle burning.")
            time.sleep(2)
            print("You try to return the relic, but the path vanishes behind you.")
            time.sleep(2)
            print("You're trapped.")
            time.sleep(2)
            print("ENDING: CURSED KEEPER (BAD ENDING)")
        elif choice_3 == "A2b":
            print("You walk away, feeling peace settle in your chest.")
            time.sleep(2)
            print("Sometimes, not taking the treasure is the true treasure.")
            time.sleep(2)
            print("ENDING: THE WISE WANDERER (NEUTRAL ENDING)")
else:
    print("You cut your way through the thick vines in Path B while also dodging the snakes and giant insects.")
    time.sleep(2)
    print("After a long time, you find ancient stone markings along the path .")
    time.sleep(2)
    print("Suddenly, you hear a growl. A panther leaps from the shadows!")
    time.sleep(2)
    print("B1: Stand your ground and use your torch to scare it off.")
    time.sleep(1)
    print("B2: Dive into a hollow log nearby to hide.")
    choice1 = input("What do you do?")
    if choice1 == "B1":
        print("You swing the torch and shout. The panther snarls, then vanishes into the trees. You breathe hard but survive.")
        time.sleep(2)
        print("You find a statue of an ancient guardian, pointing toward a cave entrance.")
        time.sleep(2)
        print("Inside, you find murals depicting the relic’s origin and a warning: “What is taken in greed will return in pain.”")
        time.sleep(2)
        print("You proceed cautiously, solve a series of booby traps, and finally reach the relic.")
        time.sleep(2)
        print("You choose to lock it in its chamber and mark the path for future generations.")
        time.sleep(2)
        print("ENDING: THE GUARDIAN'S LEGACY (??? ENDING)")
    elif choice1 == "B2":
        print("You hide in the log. The panther paces outside for what feels like hours. Then, silence.")
        time.sleep(2)
        print("But when you emerge, you realize you’re lost. You wander in circles until nightfall.")
        time.sleep(2)
        print("You climb a tree to get your bearings and slip, falling into a hidden pit.")
        time.sleep(2)
        print("At the bottom: bones, old gear, and a journal with your name on the cover.")
        time.sleep(2)
        print("ENDING: THE JUNGLE TAKES ITS OWN (??? ENDING)")
